schema_version: 1

context:
  version: 1.6.4

package:
  name: livekit-plugins-assemblyai
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/l/livekit-plugins-assemblyai/livekit_plugins_assemblyai-${{ version }}.tar.gz
    sha256: caad6c3805019e66e68873a881948b1cd99a46d4bc83a78c88f8d8111073dd4b
  - url: https://raw.githubusercontent.com/livekit/agents/refs/tags/livekit-agents%40${{ version }}/LICENSE
    sha256: c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4
    file_name: LICENSE

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - livekit-agents >=1.6.4
tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - '*'
      imports:
        - livekit.plugins.assemblyai
      pip_check: true

about:
  summary: Agent Framework plugin for AssemblyAI
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/livekit-plugins-assemblyai/
  repository: https://github.com/livekit/agents
  documentation: https://docs.livekit.io

extra:
  recipe-maintainers:
    - conda-forge/livekit
